export const MsgCacheType = {
  NEED_PROPOSE: 'NEED_PROPOSE',
  NEED_FREE_SIGNATURE: 'NEED_FREE_SIGNATURE',
  NEED_PARTNER_SIGNATURE: 'NEED_PARTNER_SIGNATURE',
  NEED_EXECUTE: 'NEED_EXECUTE',
}

export const MsgCacheStatus = {
  PARTNER_FINISHED: 'PARTNER_FINISHED',
  URGENT: 'URGENT',
}